version: "3.9"
services:
  status-hub:
    image: chilinhm/agentstatus:main
    container_name: status-hub
    restart: unless-stopped
    env_file:
      - .env
    # Gem state i en mappe
    volumes:
      - ./state:/app/state
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"